### ISSUE TITLE
Noty with requirejs

### ISSUE THREAD

**Issue by evervasquez** [needim/noty#394] opened 2017-07-14 13:55 UTC
> **_Noty version_**:  3.1.1
> **_Browser_**: .....
> **_OS_**: .....
> **_jsFiddle link (if available)_**: .....
----------
```js
requirejs.config({
    baseUrl: $path_base + 'static/js',
    paths: {
        // Core Libraries
        // --------------
        // jQuery
        "jquery": 'libs/jquery/jquery.min',
        "jquery.bootstrap": "libs/bootstrap/bootstrap.min",
        "noty": "libs/noty/lib/noty",
        ...
    }
});

define(['noty'], function (Noty) {
    return {
        show: show
    };
    function show() {
        let noty = new Noty({
            text: 'Some notification text',
        });
        return noty.show();
    }
});
//use

require([
        'jquery',
        'app/utils/noty',
], function ($, Noty) {
     	Noty.show();
});
```

Error:
Uncaught TypeError: Noty is not a constructor

any solution?

**Comment by needim** [comment] 2017-07-14 15:51
Duplicate of #378 

> Solved: if in the requirejs paths side I define "Noty": "noty.min" everything works.
I was thinking the string is arbitrary, but seems not.

**Closed** 2017-07-28 07:16 UTC
