### ISSUE TITLE
Noty not firing browser tab is active tab - multiple notifications

### ISSUE THREAD

**Issue by ganySA** [needim/noty#376] opened 2017-06-03 11:16 UTC
I am using Noty (latest version) with angular 4 on chrome (latest).

I have a settimeout method which fires every 5 minutes and checks for new values in the background. This then displays a noty letting the user know he has new messages. 

The issue i am having is that it works perfectly if this is the active window browser tab, however if it is not the active tab e.g i open www... some url ... and stay on that URL for 30 minutes when i come back to the one where noty is  and suddenly it fires all messages for the duration i was away (so for 30 minutes every 5 minutes - suddenly i get 6 notifications all displaying in one go) - they dont seem to display if the browser tab is not active - it queues them up and displays when the tab becomes active.

**Comment by fensterteam** [comment] 2017-06-04 10:55
Sounds nice. Soacial networks notifing works so.

**Comment by needim** [comment] 2017-06-04 13:57
Actually there is an option for that: visibilityControl but currently it's a little bit buggy.
More details are here: #357

Currently I'm too busy but I think next week I can work on it.

For quick fix you can commentout or remove line 2830 (it will disable all visibility control feature)
https://github.com/needim/noty/blob/master/lib/noty.js#L2830

**Comment by creage** [comment] 2017-06-26 11:38
There is another regression caused by this ``visibilityChangeFlow()`` function.

I have a main window, where I init the Noty. And I have some dialogs, that use frames, but I provide them with API to fire messages on the main window. The issue is that once the frame is activated, the ``API.PageHidden`` is set to ``true`` by the ``onBlur()`` function, and all of messages get accumulated until I close the dialog, and focus the main window back, which is just weird.

I'm not sure if I have to create a separate issue for that behavior, as you seem to know about it already.

**Comment by ernestchanjq** [comment] 2017-07-02 13:07
@creage  Yea confirm this.
I also span a iframe modal, and generate the notification, but only i click the overlay/outside iframe modal etc (parent of iframe) then the notification will start accumulate and show up.

**Comment by needim** [comment] 2017-07-12 00:19
Fixed in v3.1.1

**Closed by needim** 2017-07-12 00:19 UTC
Labels: duplicate
