### ISSUE TITLE
self.options is undefined

### ISSUE THREAD

**Issue by saper-2** [needim/noty#294] opened 2015-09-08 21:08 UTC
Hi,

I have "reinstalled" (delete dir, copy new files into) 4 times already: jquery, jquery-ui and noty. And When I try use modal:true then I get this error:
```
Error: TypeError: self.options is undefined
Source File: file:///E:/_TEMP/noty/noty-2.3.6/js/noty/packaged/jquery.noty.packaged.min.js
Line: 1
```

So when I switch to "unpacked" code then I have error with:
```
Error: TypeError: this.options.layout is undefined
Source File: http://192.168.2.31/pres/libs/noty/jquery.noty.js
Line: 38
```

And this is "Line 38":
```
this.options = $.extend({}, this.options, this.options.layout.options);
```

The error shows up also in Modal Demo .
I have FireFox 39.0 & Chrome, IE10 not work either (I don't care about IE anyway).

I checked with FireBug this line , and `this.options.layout(.options)` is undefined... 

--- edit ---
Actually this happens whenever I call noty({...}) constructor.
I use latest jquery v1.11.3 , jquery-ui v1.11.4 , noty v2.3.6 . I have tried with different noty versions and jq 1.7.2 & 1.8 - same error.
This is how I call noty, code inside `$(document).ready(function() {` :
```
	$("#b1")
		.button()
		.click(function(event) {
			var n = noty({ 
				text        : "Login or passwd can not be empty.",
				type        : "warning",
				dismissQueue: true,
				layout      : "topCenter",
				theme       : 'defaultTheme',
				timeout     : 2000,
				modal		: true,
				buttons		: [
					{ addClass: 'btn btn-primary', text: 'Ok', onClick: function ($noty) {
						$noty.close();
					}}
				]
			});
		});
```

**Comment by saper-2** [comment] 2015-09-09 19:35
Hello,

The error from title shows up every time I try to use noty :cry: (latest one, and a lite older too). The most strange thing is that demos works fine (expect modal demo), and I have include everything like in demo ,and written noty configuration exactly that same way (even copied)...

I did more "research" today to get things working, and I managed to get noty to work but I had to use quiet old noty lib which I grabbed from old project, from almost 2 years ago (1 year 9 month exactly).
The "old" noty that works for me, I have only in "packed.min.js" version, so I don't have header with version, I can only tell date of file, which is: 2014-01-21 (around 2:21 AM).

So I have old noty lib working with latest jq and jq-ui...

**Comment by kamiloBeltran** [comment] 2015-09-11 18:01
Hello,

the solution to the problem is to change the library 'jquery.noty.packaged.js' on line 419:

  modal.prependTo ($ ('body')) fadeIn (self.options.animation.fadeSpeed).;

and self change for notification

. modal.prependTo ($ ('body')) fadeIn (notification.options.animation.fadespeed);

and with this as part of modal works.

**Comment by vatoer** [comment] 2015-09-14 13:31
@kamiloBeltran 
Thank for your help, now it works with ur suggestion to change the library  'jquery.noty.packaged.js' on line 419
so i may close this issue?

**Closed** 2015-09-14 13:42 UTC
